version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - skystream

  skystream:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production