name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up Docker containers
        run: docker-compose down

      - name: Run docker-compose up in detached mode
        run: docker-compose up --build -d

      - name: Check running containers
        run: docker ps

      - name: Check skystream container logs
        run: docker logs skystream-skystream-1

      - name: Check prometheus container logs
        run: docker logs skystream-prometheus-1