name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up Docker containers
        run: docker-compose down

      - name: Run docker-compose up in detached mode
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        shell: pwsh
        run: |
          do {
            $response1 = Invoke-WebRequest -Uri http://localhost:3000/ -UseBasicParsing -ErrorAction SilentlyContinue
            $response2 = Invoke-WebRequest -Uri http://localhost:9090/query -UseBasicParsing -ErrorAction SilentlyContinue
            if ($response1.StatusCode -eq 200 -and $response2.StatusCode -eq 200) {
              break
            }
            Write-Host "Waiting for services..."
            Start-Sleep -Seconds 5
          } while ($true)

      - name: Check running containers
        run: docker ps

      - name: Check skystream container logs
        run: docker logs skystream-skystream-1

      - name: Check prometheus container logs
        run: docker logs skystream-prometheus-1